version: '3.3'
services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=Pass@123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:

